project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Hello, I'm Yang Enhui!"
  site-url: https://yangeh03.github.io
  favicon: images/favicon.ico
  repo-url: https://github.com/yangeh03/yangeh03.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    right: |
      Made with [Quarto](https://quarto.org/)<br>
      <span id="busuanzi_container_site_pv">
        本站总访问量 <span id="busuanzi_value_site_pv"></span> 次
      </span><br>
      <span id="busuanzi_container_site_uv">
        本站访客数 <span id="busuanzi_value_site_uv"></span> 人
      </span>
    
  navbar: 
    background: "#333333"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Courses"
        href: courses.qmd
      # - text: "publications"
      #   href: publications.qmd
      # - text: "Books"
      #   href: books.qmd
      - text: "Blogs/Notes"
        href: notes.qmd
      # - text: "Codes"
      #   href: codes.qmd
      - text: "Favorite"
        href: favorite.qmd
      - text: "中文"
        href: yangenhui.pdf
      - text: "CV"
        href: yangenhui.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: left  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细
    include-in-header:
      - text: |
          <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>